// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjEROD7h6Ev0kbx_Nifs_uKIus2kxmKbU',
    appId: '1:731173302233:web:a6fe4b3fa9cc36009bf3c8',
    messagingSenderId: '731173302233',
    projectId: 'flutter-basic-a2b48',
    authDomain: 'flutter-basic-a2b48.firebaseapp.com',
    storageBucket: 'flutter-basic-a2b48.appspot.com',
    measurementId: 'G-W6GFQGB5JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4B2zr7ZQwNa_iWXWn1lPs4iieE6Iw0V4',
    appId: '1:731173302233:android:deba37450bee08c59bf3c8',
    messagingSenderId: '731173302233',
    projectId: 'flutter-basic-a2b48',
    storageBucket: 'flutter-basic-a2b48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbxRflpcHXUPJlFZUZTuHcDcpaw_E-0-E',
    appId: '1:731173302233:ios:f54d9597d23bb9949bf3c8',
    messagingSenderId: '731173302233',
    projectId: 'flutter-basic-a2b48',
    storageBucket: 'flutter-basic-a2b48.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbxRflpcHXUPJlFZUZTuHcDcpaw_E-0-E',
    appId: '1:731173302233:ios:f54d9597d23bb9949bf3c8',
    messagingSenderId: '731173302233',
    projectId: 'flutter-basic-a2b48',
    storageBucket: 'flutter-basic-a2b48.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjEROD7h6Ev0kbx_Nifs_uKIus2kxmKbU',
    appId: '1:731173302233:web:c0b6bdd9f33568d69bf3c8',
    messagingSenderId: '731173302233',
    projectId: 'flutter-basic-a2b48',
    authDomain: 'flutter-basic-a2b48.firebaseapp.com',
    storageBucket: 'flutter-basic-a2b48.appspot.com',
    measurementId: 'G-HNWPJNRZFK',
  );
}
